# Generated by Django 5.2.7 on 2026-02-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
